version: '2.0'
services:
    db:
        image: postgres:12.4-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: "titbpembanmih32s"

    fib_decomp:
        build: .
        ports:
        - "5000:5000"
